version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DOTNET_CORE_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- ps: mkdir -Force ".\build\" | Out-Null
- ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2/scripts/obtain/dotnet-install.ps1" -OutFile ".\build\installcli.ps1"
- ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
- ps: '& .\build\installcli.ps1 -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath -Version 1.0.0-preview2-003131'
- ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.BootStrap\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Command\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Data.Exceptions\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.IoC\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Message\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Query\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.RabbitMQ\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Web.Mvc\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Web.Security\project.json
- dnu restore
build_script:
- ps: ./Build.ps1
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies:
    - '**\test\Spring2.Common.Test.ApplicationService.dll'
    - '**\test\Spring2.Common.Test.Domain.dll'
    - '**\test\Spring2.Common.Test.DomainService.dll'
    - '**\test\Spring2.Common.Test.Web.CustomerSite.dll'
    - '**\test\Spring2.Common.Test.DTOAssembler.dll'
    - '**\test\Spring2.Common.Test.Web.MerchantSite.dll'
    - '**\test\Spring2.Common.Test.Web.Common.dll'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '**\Spring2*.nupkg' # find all NuGet packages recursively