version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION='{version}'
- dnvm upgrade
- dnvm upgrade -r coreclr
- dnvm install 1.0.0-rc1-update1
- dnvm use 1.0.0-rc1-update1
- dnu restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies:
    - '**\test\Spring2.Common.Test.ApplicationService.dll'
    - '**\test\Spring2.Common.Test.Domain.dll'
    - '**\test\Spring2.Common.Test.DomainService.dll'
    - '**\test\Spring2.Common.Test.Web.CustomerSite.dll'
    - '**\test\Spring2.Common.Test.DTOAssembler.dll'
    - '**\test\Spring2.Common.Test.Web.MerchantSite.dll'
    - '**\test\Spring2.Common.Test.Web.Common.dll'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '**\Spring2*.nupkg' # find all NuGet packages recursively