version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dnvm upgrade
- dnvm upgrade -r coreclr
- dnvm install 1.0.0-rc1-update1
- dnvm use 1.0.0-rc1-update1
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.BootStrap\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Command\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Data.Exceptions\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.IoC\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Message\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Query\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.RabbitMQ\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Web.Mvc\project.json
- sed -i -e "s|1.0.0-\*|1.0.%APPVEYOR_BUILD_NUMBER%|g" src\Spring2.Common.Web.Security\project.json
- dnu restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies:
    - '**\test\Spring2.Common.Test.ApplicationService.dll'
    - '**\test\Spring2.Common.Test.Domain.dll'
    - '**\test\Spring2.Common.Test.DomainService.dll'
    - '**\test\Spring2.Common.Test.Web.CustomerSite.dll'
    - '**\test\Spring2.Common.Test.DTOAssembler.dll'
    - '**\test\Spring2.Common.Test.Web.MerchantSite.dll'
    - '**\test\Spring2.Common.Test.Web.Common.dll'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

artifacts:
  - path: '**\Spring2*.nupkg' # find all NuGet packages recursively